### ISSUE TITLE
Texture problems 

### ISSUE THREAD

**Issue by zef126** [HPL-Team/Project-HPL#10]
Affect the textures of other mods(octo system)...the mod can't find them!

**Comment by Slish562** [comment]
Azaria doesn't affect other mods.

**Comment by Slish562** [comment]
1. Make sure you have no other mods that could break your game.
2.  If there appears to be no other mods breaking the textures, try reinstalling both FOS and HPL.
3. Send a full log and a list of enabled modifications

**Comment by zef126** [comment]
I made a wrong diagnosis, excuse me!

**Comment by Slish562** [comment]
No porblem
