### ISSUE TITLE
Suggestion: toggle console logging of plasma node relationships

### ISSUE THREAD

**Issue by yesC48** [HPL-Team/Project-HPL#7]
Self explanatory - it should be located in settings > game and is toggled off by default.

Crash log (opening console triggers the crash because of too many log entries; this is why I opened this in the first place):
[crash_1699496279612.txt](https://github.com/HPL-Team/Project-HPL/files/13327034/crash_1699496279612.txt)

**Comment by Slish562** [comment]
Fixed
https://github.com/HPL-Team/Project-HPL/releases/tag/v0.2.3.1A
