### ISSUE TITLE
Suggestion: "Khylid Drill" item

### ISSUE THREAD

**Issue by notlinuxpeng** [HPL-Team/Project-HPL#9]
- An item suggestion to improve design!

# Description
The "Khylid Drill" item is a drill item that functions similarly to drills seen in Serpulo and can mine ground ores.

# Unlocking
It can be unlocked after the Fors Crusher, costing 60 Khylid and 100 Fors to unlock.

# Stats
- Mining speeds 
Fors: 0.75/sec
Khylid: 0.75/sec
- Other 
Build time: 0.5 secs
Cost: 25 Khylid, 30 Fors

**Comment by m1ss1onBest** [comment]
Thanks! We're working on it now. Btw how do you think to get Khylid without Khylid?

**Comment by notlinuxpeng** [comment]
Ah, should have thought of that. Maybe make it unlockable after obtaining Khylid?

**Comment by m1ss1onBest** [comment]
I'll do something with it
